<?php

namespace Database\Seeders;

use App\Models\Player;
use Illuminate\Database\Seeder;

class PlayersSeeder extends Seeder
{
    public function run()
    {
        $players = array(
            array("first_name"=>"Folarin","second_name"=>"Balogun","player_id"=>"1"),
            array("first_name"=>"Cédric","second_name"=>"Alves Soares","player_id"=>"2"),
            array("first_name"=>"Mohamed","second_name"=>"Elneny","player_id"=>"3"),
            array("first_name"=>"Fábio","second_name"=>"Ferreira Vieira","player_id"=>"4"),
            array("first_name"=>"Gabriel","second_name"=>"dos Santos Magalhães","player_id"=>"5"),
            array("first_name"=>"Kai","second_name"=>"Havertz","player_id"=>"6"),
            array("first_name"=>"Rob","second_name"=>"Holding","player_id"=>"7"),
            array("first_name"=>"Gabriel","second_name"=>"Fernando de Jesus","player_id"=>"8"),
            array("first_name"=>"Jorge Luiz","second_name"=>"Frello Filho","player_id"=>"9"),
            array("first_name"=>"Jakub","second_name"=>"Kiwior","player_id"=>"10"),
            array("first_name"=>"Marcus","second_name"=>"Oliveira Alencar","player_id"=>"11"),
            array("first_name"=>"Gabriel","second_name"=>"Martinelli Silva","player_id"=>"12"),
            array("first_name"=>"Eddie","second_name"=>"Nketiah","player_id"=>"13"),
            array("first_name"=>"Martin","second_name"=>"Ødegaard","player_id"=>"14"),
            array("first_name"=>"Thomas","second_name"=>"Partey","player_id"=>"15"),
            array("first_name"=>"Nicolas","second_name"=>"Pépé","player_id"=>"16"),
            array("first_name"=>"Aaron","second_name"=>"Ramsdale","player_id"=>"17"),
            array("first_name"=>"Rúnar Alex","second_name"=>"Rúnarsson","player_id"=>"18"),
            array("first_name"=>"Bukayo","second_name"=>"Saka","player_id"=>"19"),
            array("first_name"=>"William","second_name"=>"Saliba","player_id"=>"20"),
            array("first_name"=>"Albert","second_name"=>"Sambi Lokonga","player_id"=>"21"),
            array("first_name"=>"Emile","second_name"=>"Smith Rowe","player_id"=>"22"),
            array("first_name"=>"Nuno","second_name"=>"Varela Tavares","player_id"=>"23"),
            array("first_name"=>"Kieran","second_name"=>"Tierney","player_id"=>"24"),
            array("first_name"=>"Takehiro","second_name"=>"Tomiyasu","player_id"=>"25"),
            array("first_name"=>"Leandro","second_name"=>"Trossard","player_id"=>"26"),
            array("first_name"=>"Matt","second_name"=>"Turner","player_id"=>"28"),
            array("first_name"=>"Benjamin","second_name"=>"White","player_id"=>"29"),
            array("first_name"=>"Granit","second_name"=>"Xhaka","player_id"=>"30"),
            array("first_name"=>"Oleksandr","second_name"=>"Zinchenko","player_id"=>"31"),
            array("first_name"=>"Declan","second_name"=>"Rice","player_id"=>"540"),
            array("first_name"=>"Reiss","second_name"=>"Nelson","player_id"=>"578"),
            array("first_name"=>"Jurriën","second_name"=>"Timber","player_id"=>"585"),
            array("first_name"=>"Alexandre","second_name"=>"Moreno Lopera","player_id"=>"32"),
            array("first_name"=>"Leon","second_name"=>"Bailey","player_id"=>"34"),
            array("first_name"=>"Emiliano","second_name"=>"Buendía Stati","player_id"=>"35"),
            array("first_name"=>"Matty","second_name"=>"Cash","player_id"=>"36"),
            array("first_name"=>"Calum","second_name"=>"Chambers","player_id"=>"37"),
            array("first_name"=>"Philippe","second_name"=>"Coutinho Correia","player_id"=>"38"),
            array("first_name"=>"Keinan","second_name"=>"Davis","player_id"=>"39"),
            array("first_name"=>"Leander","second_name"=>"Dendoncker","player_id"=>"40"),
            array("first_name"=>"Cameron","second_name"=>"Archer","player_id"=>"33"),
            array("first_name"=>"Diego Carlos","second_name"=>"Santos Silva","player_id"=>"41"),
            array("first_name"=>"Lucas","second_name"=>"Digne","player_id"=>"42"),
            array("first_name"=>"Douglas Luiz","second_name"=>"Soares de Paulo","player_id"=>"43"),
            array("first_name"=>"Jhon","second_name"=>"Durán","player_id"=>"44"),
            array("first_name"=>"Kortney","second_name"=>"Hause","player_id"=>"45"),
            array("first_name"=>"Tim","second_name"=>"Iroegbunam","player_id"=>"46"),
            array("first_name"=>"Boubacar","second_name"=>"Kamara","player_id"=>"47"),
            array("first_name"=>"Ezri","second_name"=>"Konsa Ngoyo","player_id"=>"48"),
            array("first_name"=>"Emiliano","second_name"=>"Martínez Romero","player_id"=>"49"),
            array("first_name"=>"John","second_name"=>"McGinn","player_id"=>"50"),
            array("first_name"=>"Tyrone","second_name"=>"Mings","player_id"=>"51"),
            array("first_name"=>"Robin","second_name"=>"Olsen","player_id"=>"53"),
            array("first_name"=>"Jaden","second_name"=>"Philogene-Bplayer_idace","player_id"=>"54"),
            array("first_name"=>"Jacob","second_name"=>"Ramsey","player_id"=>"55"),
            array("first_name"=>"Morgan","second_name"=>"Sanson","player_id"=>"56"),
            array("first_name"=>"Viljami","second_name"=>"Sinisalo","player_id"=>"57"),
            array("first_name"=>"Youri","second_name"=>"Tielemans","player_id"=>"58"),
            array("first_name"=>"Bertrand","second_name"=>"Traoré","player_id"=>"59"),
            array("first_name"=>"Ollie","second_name"=>"Watkins","player_id"=>"60"),
            array("first_name"=>"Wesley","second_name"=>"Moraes Ferreira da Silva","player_id"=>"61"),
            array("first_name"=>"Pau","second_name"=>"Torres","player_id"=>"584"),
            array("first_name"=>"Moussa","second_name"=>"Diaby","player_id"=>"599"),
            array("first_name"=>"Japlayer_idon","second_name"=>"Anthony","player_id"=>"62"),
            array("first_name"=>"Philip","second_name"=>"Billing","player_id"=>"63"),
            array("first_name"=>"Davplayer_id","second_name"=>"Brooks","player_id"=>"64"),
            array("first_name"=>"Ryan","second_name"=>"Christie","player_id"=>"65"),
            array("first_name"=>"Lewis","second_name"=>"Cook","player_id"=>"66"),
            array("first_name"=>"Siriki","second_name"=>"Dembélé","player_id"=>"67"),
            array("first_name"=>"Ryan","second_name"=>"Fredericks","player_id"=>"68"),
            array("first_name"=>"James","second_name"=>"Hill","player_id"=>"69"),
            array("first_name"=>"Lloyd","second_name"=>"Kelly","player_id"=>"70"),
            array("first_name"=>"Gavin","second_name"=>"Kilkenny","player_id"=>"71"),
            array("first_name"=>"Justin","second_name"=>"Kluivert","player_id"=>"72"),
            array("first_name"=>"Jamal","second_name"=>"Lowe","player_id"=>"73"),
            array("first_name"=>"Emiliano","second_name"=>"Marcondes","player_id"=>"74"),
            array("first_name"=>"Chris","second_name"=>"Mepham","player_id"=>"75"),
            array("first_name"=>"Kieffer","second_name"=>"Moore","player_id"=>"76"),
            array("first_name"=>"Norberto","second_name"=>"Murara Neto","player_id"=>"77"),
            array("first_name"=>"Dango","second_name"=>"Ouattara","player_id"=>"78"),
            array("first_name"=>"Ben","second_name"=>"Pearson","player_id"=>"79"),
            array("first_name"=>"Darren","second_name"=>"Randolph","player_id"=>"80"),
            array("first_name"=>"Joe","second_name"=>"Rothwell","player_id"=>"81"),
            array("first_name"=>"Antoine","second_name"=>"Semenyo","player_id"=>"82"),
            array("first_name"=>"Marcos","second_name"=>"Senesi","player_id"=>"83"),
            array("first_name"=>"Adam","second_name"=>"Smith","player_id"=>"84"),
            array("first_name"=>"Dominic","second_name"=>"Solanke","player_id"=>"85"),
            array("first_name"=>"Marcus","second_name"=>"Tavernier","player_id"=>"86"),
            array("first_name"=>"Hamed","second_name"=>"Traorè","player_id"=>"87"),
            array("first_name"=>"Mark","second_name"=>"Travers","player_id"=>"88"),
            array("first_name"=>"Illia","second_name"=>"Zabarnyi","player_id"=>"89"),
            array("first_name"=>"Milos","second_name"=>"Kerkez","player_id"=>"595"),
            array("first_name"=>"Ionuț","second_name"=>"Radu","player_id"=>"607"),
            array("first_name"=>"Kristoffer","second_name"=>"Ajer","player_id"=>"90"),
            array("first_name"=>"Ellery","second_name"=>"Balcombe","player_id"=>"91"),
            array("first_name"=>"Shandon","second_name"=>"Baptiste","player_id"=>"92"),
            array("first_name"=>"Mads","second_name"=>"Bech Sørensen","player_id"=>"93"),
            array("first_name"=>"Mads","second_name"=>"Bplayer_idstrup","player_id"=>"94"),
            array("first_name"=>"Sergi","second_name"=>"Canós Tenés","player_id"=>"95"),
            array("first_name"=>"Nathan","second_name"=>"Collins","player_id"=>"96"),
            array("first_name"=>"Matthew","second_name"=>"Cox","player_id"=>"97"),
            array("first_name"=>"Mikkel","second_name"=>"Damsgaard","player_id"=>"98"),
            array("first_name"=>"Josh","second_name"=>"Dasilva","player_id"=>"99"),
            array("first_name"=>"Halil","second_name"=>"Dervişoğlu","player_id"=>"100"),
            array("first_name"=>"Mark","second_name"=>"Flekken","player_id"=>"101"),
            array("first_name"=>"Charlie","second_name"=>"Goode","player_id"=>"102"),
            array("first_name"=>"Rico","second_name"=>"Henry","player_id"=>"103"),
            array("first_name"=>"Aaron","second_name"=>"Hickey","player_id"=>"104"),
            array("first_name"=>"Vitaly","second_name"=>"Janelt","player_id"=>"105"),
            array("first_name"=>"Mathias","second_name"=>"Jensen","player_id"=>"106"),
            array("first_name"=>"Keane","second_name"=>"Lewis-Potter","player_id"=>"107,"),
            array("first_name"=>"Bryan","second_name"=>"Mbeumo","player_id"=>"108"),
            array("first_name"=>"Ben","second_name"=>"Mee","player_id"=>"109"),
            array("first_name"=>"Christian","second_name"=>"Nørgaard","player_id"=>"110"),
            array("first_name"=>"Frank","second_name"=>"Onyeka","player_id"=>"111"),
            array("first_name"=>"Ethan","second_name"=>"Pinnock","player_id"=>"112"),
            array("first_name"=>"Davplayer_id","second_name"=>"Raya Martin","player_id"=>"113"),
            array("first_name"=>"Mads","second_name"=>"Roerslev Rasmussen","player_id"=>"114"),
            array("first_name"=>"Kevin","second_name"=>"Schade","player_id"=>"115"),
            array("first_name"=>"Thomas","second_name"=>"Strakosha","player_id"=>"116"),
            array("first_name"=>"Ivan","second_name"=>"Toney","player_id"=>"117"),
            array("first_name"=>"Ryan","second_name"=>"Trevitt","player_id"=>"118"),
            array("first_name"=>"Yoane","second_name"=>"Wissa","player_id"=>"119"),
            array("first_name"=>"Yegor","second_name"=>"Yarmolyuk","player_id"=>"120"),
            array("first_name"=>"Mathias","second_name"=>"Jorgensen","player_id"=>"121"),
            array("first_name"=>"Simon","second_name"=>"Adingra","player_id"=>"122"),
            array("first_name"=>"Steven","second_name"=>"Alzate","player_id"=>"123"),
            array("first_name"=>"Yasin","second_name"=>"Ayari","player_id"=>"124"),
            array("first_name"=>"Facundo","second_name"=>"Buonanotte","player_id"=>"125"),
            array("first_name"=>"Moisés","second_name"=>"Caicedo Corozo","player_id"=>"126"),
            array("first_name"=>"Aaron","second_name"=>"Connolly","player_id"=>"127"),
            array("first_name"=>"Mahmoud","second_name"=>"Dahoud","player_id"=>"128"),
            array("first_name"=>"Lewis","second_name"=>"Dunk","player_id"=>"129"),
            array("first_name"=>"Julio","second_name"=>"Enciso","player_id"=>"130"),
            array("first_name"=>"Pervis","second_name"=>"Estupiñán","player_id"=>"131"),
            array("first_name"=>"Evan","second_name"=>"Ferguson","player_id"=>"132"),
            array("first_name"=>"Billy","second_name"=>"Gilmour","player_id"=>"133"),
            array("first_name"=>"Pascal","second_name"=>"Groß","player_id"=>"134"),
            array("first_name"=>"João Pedro","second_name"=>"Junqueira de Jesus","player_id"=>"135"),
            array("first_name"=>"Michał","second_name"=>"Karbownik","player_id"=>"136"),
            array("first_name"=>"Kacper","second_name"=>"Kozłowski","player_id"=>"137"),
            array("first_name"=>"Adam","second_name"=>"Lallana","player_id"=>"138"),
            array("first_name"=>"Tariq","second_name"=>"Lamptey","player_id"=>"139"),
            array("first_name"=>"Solly","second_name"=>"March","player_id"=>"140"),
            array("first_name"=>"Tom","second_name"=>"McGill","player_id"=>"141"),
            array("first_name"=>"James","second_name"=>"Milner","player_id"=>"142"),
            array("first_name"=>"Kaoru","second_name"=>"Mitoma","player_id"=>"143"),
            array("first_name"=>"Jakub","second_name"=>"Moder","player_id"=>"144"),
            array("first_name"=>"Jeremy","second_name"=>"Sarmiento Morante","player_id"=>"146"),
            array("first_name"=>"Kjell","second_name"=>"Scherpen","player_id"=>"147"),
            array("first_name"=>"Jason","second_name"=>"Steele","player_id"=>"148"),
            array("first_name"=>"Deniz","second_name"=>"Undav","player_id"=>"149"),
            array("first_name"=>"Jan Paul","second_name"=>"van Hecke","player_id"=>"150"),
            array("first_name"=>"Joël","second_name"=>"Veltman","player_id"=>"151"),
            array("first_name"=>"Bart","second_name"=>"Verbruggen","player_id"=>"152"),
            array("first_name"=>"Adam","second_name"=>"Webster","player_id"=>"153"),
            array("first_name"=>"Danny","second_name"=>"Welbeck","player_id"=>"154"),
            array("first_name"=>"Andi","second_name"=>"Zeqiri","player_id"=>"155"),
            array("first_name"=>"Igor Julio","second_name"=>"dos Santos de Paulo","player_id"=>"606"),
            array("first_name"=>"Enock","second_name"=>"Agyei","player_id"=>"156"),
            array("first_name"=>"Ameen","second_name"=>"Al-Dakhil","player_id"=>"157,"),
            array("first_name"=>"Samuel","second_name"=>"Bastien","player_id"=>"158"),
            array("first_name"=>"Manuel Benson","second_name"=>"Hedilazio","player_id"=>"159"),
            array("first_name"=>"Jordan","second_name"=>"Beyer","player_id"=>"160"),
            array("first_name"=>"Josh","second_name"=>"Brownhill","player_id"=>"161"),
            array("first_name"=>"Darko","second_name"=>"Churlinov","player_id"=>"162"),
            array("first_name"=>"Jack","second_name"=>"Cork","player_id"=>"163"),
            array("first_name"=>"Dara","second_name"=>"Costelloe","player_id"=>"164"),
            array("first_name"=>"Josh","second_name"=>"Cullen","player_id"=>"165"),
            array("first_name"=>"CJ","second_name"=>"Egan-Riley","player_id"=>"166"),
            array("first_name"=>"Hjalmar","second_name"=>"Ekdal","player_id"=>"167"),
            array("first_name"=>"Lyle","second_name"=>"Foster","player_id"=>"168"),
            array("first_name"=>"Denis","second_name"=>"Franchi","player_id"=>"169"),
            array("first_name"=>"Jóhann Berg","second_name"=>"Gudmundsson","player_id"=>"170"),
            array("first_name"=>"Luke","second_name"=>"McNally","player_id"=>"171"),
            array("first_name"=>"Arijanet","second_name"=>"Muric","player_id"=>"172"),
            array("first_name"=>"Dara","second_name"=>"O'Shea","player_id"=>"173,"),
            array("first_name"=>"Michael","second_name"=>"Obafemi","player_id"=>"174"),
            array("first_name"=>"Bailey","second_name"=>"Peacock-Farrell","player_id"=>"175"),
            array("first_name"=>"Connor","second_name"=>"Roberts","player_id"=>"176"),
            array("first_name"=>"Jay","second_name"=>"Rodriguez","player_id"=>"177"),
            array("first_name"=>"Charlie","second_name"=>"Taylor","player_id"=>"178"),
            array("first_name"=>"Bobby","second_name"=>"Thomas","player_id"=>"179"),
            array("first_name"=>"Scott","second_name"=>"Twine","player_id"=>"180"),
            array("first_name"=>"Lawrence","second_name"=>"Vigouroux","player_id"=>"181"),
            array("first_name"=>"Victor","second_name"=>"da Silva","player_id"=>"182"),
            array("first_name"=>"Wout","second_name"=>"Weghorst","player_id"=>"183"),
            array("first_name"=>"Anass","second_name"=>"Zaroury","player_id"=>"184"),
            array("first_name"=>"Zeki","second_name"=>"Amdouni","player_id"=>"594"),
            array("first_name"=>"James","second_name"=>"Trafford","player_id"=>"596"),
            array("first_name"=>"Nathan","second_name"=>"Redmond","player_id"=>"600"),
            array("first_name"=>"Luca","second_name"=>"Koleosho","player_id"=>"605"),
            array("first_name"=>"Jacob","second_name"=>"Bruun Larsen","player_id"=>"608"),
            array("first_name"=>"Robert","second_name"=>"Sánchez","player_id"=>"145"),
            array("first_name"=>"Ethan","second_name"=>"Ampadu","player_id"=>"185"),
            array("first_name"=>"Andrey","second_name"=>"Nascimento dos Santos","player_id"=>"186"),
            array("first_name"=>"Kepa","second_name"=>"Arrizabalaga","player_id"=>"187"),
            array("first_name"=>"Pierre-Emerick","second_name"=>"Aubameyang","player_id"=>"188"),
            array("first_name"=>"César","second_name"=>"Azpilicueta","player_id"=>"189"),
            array("first_name"=>"Abdul Rahman","second_name"=>"Baba","player_id"=>"190"),
            array("first_name"=>"Benoît","second_name"=>"Badiashile","player_id"=>"191"),
            array("first_name"=>"Marcus","second_name"=>"Bettinelli","player_id"=>"192"),
            array("first_name"=>"Armando","second_name"=>"Broja","player_id"=>"193"),
            array("first_name"=>"Trevoh","second_name"=>"Chalobah","player_id"=>"194"),
            array("first_name"=>"Ben","second_name"=>"Chilwell","player_id"=>"195"),
            array("first_name"=>"Carney","second_name"=>"Chukwuemeka","player_id"=>"196"),
            array("first_name"=>"Levi","second_name"=>"Colwill","player_id"=>"197"),
            array("first_name"=>"Marc","second_name"=>"Cucurella Saseta","player_id"=>"198"),
            array("first_name"=>"Enzo","second_name"=>"Fernández","player_id"=>"199"),
            array("first_name"=>"Davplayer_id Datro","second_name"=>"Fofana","player_id"=>"200"),
            array("first_name"=>"Wesley","second_name"=>"Fofana","player_id"=>"201"),
            array("first_name"=>"Conor","second_name"=>"Gallagher","player_id"=>"202"),
            array("first_name"=>"Malo","second_name"=>"Gusto","player_id"=>"203"),
            array("first_name"=>"Lewis","second_name"=>"Hall","player_id"=>"204"),
            array("first_name"=>"Callum","second_name"=>"Hudson-Odoi","player_id"=>"205"),
            array("first_name"=>"Reece","second_name"=>"James","player_id"=>"206"),
            array("first_name"=>"Romelu","second_name"=>"Lukaku Bolingoli","player_id"=>"207"),
            array("first_name"=>"Noni","second_name"=>"Madueke","player_id"=>"208"),
            array("first_name"=>"Mykhailo","second_name"=>"Mudryk","player_id"=>"210"),
            array("first_name"=>"Nicolas","second_name"=>"Jackson","player_id"=>"211"),
            array("first_name"=>"Christopher","second_name"=>"Nkunku","player_id"=>"212"),
            array("first_name"=>"Christian","second_name"=>"Pulisic","player_id"=>"213"),
            array("first_name"=>"Malang","second_name"=>"Sarr","player_id"=>"214"),
            array("first_name"=>"Gabriel","second_name"=>"Słonina","player_id"=>"215"),
            array("first_name"=>"Raheem","second_name"=>"Sterling","player_id"=>"216"),
            array("first_name"=>"Thiago","second_name"=>"Emiliano da Silva","player_id"=>"217"),
            array("first_name"=>"Hakim","second_name"=>"Ziyech","player_id"=>"218"),
            array("first_name"=>"Ângelo Gabriel","second_name"=>"Borges Damaceno","player_id"=>"589"),
            array("first_name"=>"Ian","second_name"=>"Maatsen","player_id"=>"609"),
            array("first_name"=>"Axel","second_name"=>"Disasi","player_id"=>"611"),
            array("first_name"=>"Lesley","second_name"=>"Ugochukwu","player_id"=>"613"),
            array("first_name"=>"Naouirou","second_name"=>"Ahamada","player_id"=>"219"),
            array("first_name"=>"Joachim","second_name"=>"Andersen","player_id"=>"220"),
            array("first_name"=>"Jordan","second_name"=>"Ayew","player_id"=>"221"),
            array("first_name"=>"Nathaniel","second_name"=>"Clyne","player_id"=>"222"),
            array("first_name"=>"Cheick","second_name"=>"Doucouré","player_id"=>"223"),
            array("first_name"=>"Malcolm","second_name"=>"Ebiowei","player_id"=>"224"),
            array("first_name"=>"Odsonne","second_name"=>"Edouard","player_id"=>"225"),
            array("first_name"=>"Eberechi","second_name"=>"Eze","player_id"=>"226"),
            array("first_name"=>"Vicente","second_name"=>"Guaita","player_id"=>"227"),
            array("first_name"=>"Marc","second_name"=>"Guéhi","player_id"=>"228"),
            array("first_name"=>"Will","second_name"=>"Hughes","player_id"=>"229"),
            array("first_name"=>"Sam","second_name"=>"Johnstone","player_id"=>"230"),
            array("first_name"=>"Jefferson","second_name"=>"Lerma Solís","player_id"=>"231"),
            array("first_name"=>"Jean-Philippe","second_name"=>"Mateta","player_id"=>"232"),
            array("first_name"=>"Remi","second_name"=>"Matthews","player_id"=>"233"),
            array("first_name"=>"Tyrick","second_name"=>"Mitchell","player_id"=>"234"),
            array("first_name"=>"Jake","second_name"=>"O'Brien","player_id"=>"235"),
            array("first_name"=>"Michael","second_name"=>"Olise","player_id"=>"236"),
            array("first_name"=>"Luke","second_name"=>"Plange","player_id"=>"237"),
            array("first_name"=>"Chris","second_name"=>"Richards","player_id"=>"238"),
            array("first_name"=>"Jairo","second_name"=>"Riedewald","player_id"=>"239"),
            array("first_name"=>"Jeffrey","second_name"=>"Schlupp","player_id"=>"240"),
            array("first_name"=>"James","second_name"=>"Tomkins","player_id"=>"241"),
            array("first_name"=>"Joel","second_name"=>"Ward","player_id"=>"242"),
            array("first_name"=>"Joe","second_name"=>"Whitworth","player_id"=>"243"),
            array("first_name"=>"Matheus","second_name"=>"França de Oliveira","player_id"=>"615"),
            array("first_name"=>"André","second_name"=>"Tavares Gomes","player_id"=>"244"),
            array("first_name"=>"Jarrad","second_name"=>"Branthwaite","player_id"=>"245"),
            array("first_name"=>"Dominic","second_name"=>"Calvert-Lewin","player_id"=>"246"),
            array("first_name"=>"Seamus","second_name"=>"Coleman","player_id"=>"247"),
            array("first_name"=>"Dele","second_name"=>"Alli","player_id"=>"248"),
            array("first_name"=>"Abdoulaye","second_name"=>"Doucouré","player_id"=>"249"),
            array("first_name"=>"James","second_name"=>"Garner","player_id"=>"250"),
            array("first_name"=>"Jean-Philippe","second_name"=>"Gbamin","player_id"=>"251"),
            array("first_name"=>"Ben","second_name"=>"Godfrey","player_id"=>"252"),
            array("first_name"=>"Demarai","second_name"=>"Gray","player_id"=>"253"),
            array("first_name"=>"player_idrissa","second_name"=>"Gueye","player_id"=>"254"),
            array("first_name"=>"Mason","second_name"=>"Holgate","player_id"=>"255"),
            array("first_name"=>"Alex","second_name"=>"Iwobi","player_id"=>"256"),
            array("first_name"=>"Michael","second_name"=>"Keane","player_id"=>"257"),
            array("first_name"=>"Neal","second_name"=>"Maupay","player_id"=>"258"),
            array("first_name"=>"Dwight","second_name"=>"McNeil","player_id"=>"259"),
            array("first_name"=>"Vitalii","second_name"=>"Mykolenko","player_id"=>"260"),
            array("first_name"=>"Amadou","second_name"=>"Onana","player_id"=>"261"),
            array("first_name"=>"Nathan","second_name"=>"Patterson","player_id"=>"262"),
            array("first_name"=>"Jordan","second_name"=>"Pickford","player_id"=>"263"),
            array("first_name"=>"Ellis","second_name"=>"Simms","player_id"=>"264"),
            array("first_name"=>"James","second_name"=>"Tarkowski","player_id"=>"265"),
            array("first_name"=>"João","second_name"=>"Neves Virgínia","player_id"=>"266"),
            array("first_name"=>"Andy","second_name"=>"Lonergan","player_id"=>"579"),
            array("first_name"=>"Ashley","second_name"=>"Young","player_id"=>"588"),
            array("first_name"=>"Arnaut","second_name"=>"Danjuma Groeneveld","player_id"=>"601"),
            array("first_name"=>"Andreas","second_name"=>"Hoelgebaum Pereira","player_id"=>"267"),
            array("first_name"=>"Tom","second_name"=>"Cairney","player_id"=>"268"),
            array("first_name"=>"Ivan","second_name"=>"Neves Abreu Cavaleiro","player_id"=>"269"),
            array("first_name"=>"Bobby","second_name"=>"De Cordova-Replayer_id","player_id"=>",270"),
            array("first_name"=>"Issa","second_name"=>"Diop","player_id"=>"271"),
            array("first_name"=>"Tyrese","second_name"=>"Francois","player_id"=>"272"),
            array("first_name"=>"Anthony","second_name"=>"Knockaert","player_id"=>"273"),
            array("first_name"=>"Terence","second_name"=>"Kongolo","player_id"=>"274"),
            array("first_name"=>"Bernd","second_name"=>"Leno","player_id"=>"275"),
            array("first_name"=>"Saša","second_name"=>"Lukić","player_id"=>"276"),
            array("first_name"=>"Kevin","second_name"=>"Mbabu","player_id"=>"277"),
            array("first_name"=>"Aleksandar","second_name"=>"Mitrović","player_id"=>"278"),
            array("first_name"=>"Rodrigo","second_name"=>"Muniz Carvalho","player_id"=>"279"),
            array("first_name"=>"João","second_name"=>"Palhinha Gonçalves","player_id"=>"280"),
            array("first_name"=>"Tim","second_name"=>"Ream","player_id"=>"281"),
            array("first_name"=>"Harrison","second_name"=>"Reed","player_id"=>"282"),
            array("first_name"=>"Antonee","second_name"=>"Robinson","player_id"=>"283"),
            array("first_name"=>"Marek","second_name"=>"Rodák","player_id"=>"284"),
            array("first_name"=>"Kenny","second_name"=>"Tete","player_id"=>"285"),
            array("first_name"=>"Tosin","second_name"=>"Adarabioyo","player_id"=>"286"),
            array("first_name"=>"Carlos Vinícius","second_name"=>"Alves Morais","player_id"=>"287"),
            array("first_name"=>"Harry","second_name"=>"Wilson","player_id"=>"288"),
            array("first_name"=>"Raúl","second_name"=>"Jiménez","player_id"=>"558"),
            array("first_name"=>"Willian","second_name"=>"Borges da Silva","player_id"=>"591"),
            array("first_name"=>"Calvin","second_name"=>"Bassey","player_id"=>"610"),
            array("first_name"=>"Adrián","second_name"=>"San Miguel del Castillo","player_id"=>"289"),
            array("first_name"=>"Trent","second_name"=>"Alexander-Arnold","player_id"=>"290"),
            array("first_name"=>"Alisson","second_name"=>"Ramses Becker","player_id"=>"291"),
            array("first_name"=>"Stefan","second_name"=>"Bajcetic","player_id"=>"292"),
            array("first_name"=>"Darwin","second_name"=>"Núñez Ribeiro","player_id"=>"293"),
            array("first_name"=>"Diogo","second_name"=>"Teixeira da Silva","player_id"=>"294"),
            array("first_name"=>"Harvey","second_name"=>"Elliott","player_id"=>"295"),
            array("first_name"=>"Fabio Henrique","second_name"=>"Tavares","player_id"=>"296"),
            array("first_name"=>"Cody","second_name"=>"Gakpo","player_id"=>"297"),
            array("first_name"=>"Joe","second_name"=>"Gomez","player_id"=>"298"),
            array("first_name"=>"Jordan","second_name"=>"Henderson","player_id"=>"299"),
            array("first_name"=>"Curtis","second_name"=>"Jones","player_id"=>"300"),
            array("first_name"=>"Caoimhin","second_name"=>"Kelleher","player_id"=>"301"),
            array("first_name"=>"Ibrahima","second_name"=>"Konaté","player_id"=>"302"),
            array("first_name"=>"Luis","second_name"=>"Díaz","player_id"=>"303"),
            array("first_name"=>"Alexis","second_name"=>"Mac Allister","player_id"=>"304"),
            array("first_name"=>"Joel","second_name"=>"Matip","player_id"=>"305"),
            array("first_name"=>"Nathaniel","second_name"=>"Phillips","player_id"=>"306"),
            array("first_name"=>"Andrew","second_name"=>"Robertson","player_id"=>"307"),
            array("first_name"=>"Mohamed","second_name"=>"Salah","player_id"=>"308"),
            array("first_name"=>"Dominik","second_name"=>"Szoboszlai","player_id"=>"309"),
            array("first_name"=>"Thiago","second_name"=>"Alcántara do Nascimento","player_id"=>"310"),
            array("first_name"=>"Konstantinos","second_name"=>"Tsimikas","player_id"=>"311"),
            array("first_name"=>"Sepp","second_name"=>"van den Berg","player_id"=>"312"),
            array("first_name"=>"Virgil","second_name"=>"van Dijk","player_id"=>"313"),
            array("first_name"=>"Marvelous","second_name"=>"Nakamba","player_id"=>"52"),
            array("first_name"=>"Elijah","second_name"=>"Adebayo","player_id"=>"314"),
            array("first_name"=>"Mads Juel","second_name"=>"Andersen","player_id"=>"315"),
            array("first_name"=>"Amari'i","second_name"=>"Bell","player_id"=>"316"),
            array("first_name"=>"Luke","second_name"=>"Berry","player_id"=>"317"),
            array("first_name"=>"Reece","second_name"=>"Burke","player_id"=>"318"),
            array("first_name"=>"Allan","second_name"=>"Campbell","player_id"=>"319"),
            array("first_name"=>"Jordan","second_name"=>"Clark","player_id"=>"320"),
            array("first_name"=>"Alfie","second_name"=>"Doughty","player_id"=>"321"),
            array("first_name"=>"Luke","second_name"=>"Freeman","player_id"=>"322"),
            array("first_name"=>"Matt","second_name"=>"Macey","player_id"=>"323"),
            array("first_name"=>"John","second_name"=>"McAtee","player_id"=>"324"),
            array("first_name"=>"Carlos","second_name"=>"Mendes Gomes","player_id"=>"325"),
            array("first_name"=>"Carlton","second_name"=>"Morris","player_id"=>"326"),
            array("first_name"=>"Admiral","second_name"=>"Muskwe","player_id"=>"327"),
            array("first_name"=>"Chiedozie","second_name"=>"Ogbene","player_id"=>"328"),
            array("first_name"=>"Fred","second_name"=>"Onyedinma","player_id"=>"329"),
            array("first_name"=>"Gabriel","second_name"=>"Osho","player_id"=>"330"),
            array("first_name"=>"Aribim","second_name"=>"Pepple","player_id"=>"331"),
            array("first_name"=>"Dion","second_name"=>"Pereira","player_id"=>"332"),
            array("first_name"=>"Dan","second_name"=>"Potts","player_id"=>"333"),
            array("first_name"=>"Glen","second_name"=>"Rea","player_id"=>"334"),
            array("first_name"=>"James","second_name"=>"Shea","player_id"=>"335"),
            array("first_name"=>"Joe","second_name"=>"Taylor","player_id"=>"336"),
            array("first_name"=>"Elliot","second_name"=>"Thorpe","player_id"=>"337"),
            array("first_name"=>"Jack","second_name"=>"Walton","player_id"=>"338"),
            array("first_name"=>"Louie","second_name"=>"Watson","player_id"=>"339"),
            array("first_name"=>"Cauley","second_name"=>"Woodrow","player_id"=>"340"),
            array("first_name"=>"Ryan","second_name"=>"Giles","player_id"=>"553"),
            array("first_name"=>"Tom","second_name"=>"Lockyer","player_id"=>"575"),
            array("first_name"=>"Pelly Ruddock","second_name"=>"Mpanzu","player_id"=>"582"),
            array("first_name"=>"Tahith","second_name"=>"Chong","player_id"=>"586"),
            array("first_name"=>"Issa","second_name"=>"Kaboré","player_id"=>"602"),
            array("first_name"=>"Thomas","second_name"=>"Kaminski","player_id"=>"614"),
            array("first_name"=>"Manuel","second_name"=>"Akanji","player_id"=>"341"),
            array("first_name"=>"Nathan","second_name"=>"Aké","player_id"=>"342"),
            array("first_name"=>"Julián","second_name"=>"Álvarez","player_id"=>"343"),
            array("first_name"=>"Bernardo","second_name"=>"Veiga de Carvalho e Silva","player_id"=>"344"),
            array("first_name"=>"Oscar","second_name"=>"Bobb","player_id"=>"345"),
            array("first_name"=>"João","second_name"=>"Cancelo","player_id"=>"346"),
            array("first_name"=>"Scott","second_name"=>"Carson","player_id"=>"347"),
            array("first_name"=>"Shea","second_name"=>"Charles","player_id"=>"348"),
            array("first_name"=>"Kevin","second_name"=>"De Bruyne","player_id"=>"349"),
            array("first_name"=>"Rúben","second_name"=>"Gato Alves Dias","player_id"=>"350"),
            array("first_name"=>"Tommy","second_name"=>"Doyle","player_id"=>"351"),
            array("first_name"=>"Ederson","second_name"=>"Santana de Moraes","player_id"=>"352"),
            array("first_name"=>"Phil","second_name"=>"Foden","player_id"=>"353"),
            array("first_name"=>"Jack","second_name"=>"Grealish","player_id"=>"354"),
            array("first_name"=>"Erling","second_name"=>"Haaland","player_id"=>"355"),
            array("first_name"=>"Mateo","second_name"=>"Kovačić","player_id"=>"356"),
            array("first_name"=>"Aymeric","second_name"=>"Laporte","player_id"=>"357"),
            array("first_name"=>"Rico","second_name"=>"Lewis","player_id"=>"358"),
            array("first_name"=>"Riyad","second_name"=>"Mahrez","player_id"=>"359"),
            array("first_name"=>"James","second_name"=>"McAtee","player_id"=>"360"),
            array("first_name"=>"Stefan","second_name"=>"Ortega Moreno","player_id"=>"361"),
            array("first_name"=>"Cole","second_name"=>"Palmer","player_id"=>"362"),
            array("first_name"=>"Máximo","second_name"=>"Perrone","player_id"=>"363"),
            array("first_name"=>"Kalvin","second_name"=>"Phillips","player_id"=>"364"),
            array("first_name"=>"Rodrigo","second_name"=>"Hernandez","player_id"=>"365"),
            array("first_name"=>"Sergio","second_name"=>"Gómez","player_id"=>"366"),
            array("first_name"=>"Zack","second_name"=>"Steffen","player_id"=>"367"),
            array("first_name"=>"John","second_name"=>"Stones","player_id"=>"368"),
            array("first_name"=>"Kyle","second_name"=>"Walker","player_id"=>"369"),
            array("first_name"=>"Joško","second_name"=>"Gvardiol","player_id"=>"616"),
            array("first_name"=>"Mason","second_name"=>"Mount","player_id"=>"209"),
            array("first_name"=>"Alex","second_name"=>"Telles","player_id"=>"370"),
            array("first_name"=>"Amad","second_name"=>"Diallo","player_id"=>"371"),
            array("first_name"=>"Antony Matheus","second_name"=>"dos Santos","player_id"=>"372"),
            array("first_name"=>"Bruno","second_name"=>"Borges Fernandes","player_id"=>"373"),
            array("first_name"=>"Brandon","second_name"=>"Williams","player_id"=>"374"),
            array("first_name"=>"Eric","second_name"=>"Bailly","player_id"=>"375"),
            array("first_name"=>"Carlos Henrique","second_name"=>"Casimiro","player_id"=>"376"),
            array("first_name"=>"Diogo","second_name"=>"Dalot Teixeira","player_id"=>"377"),
            array("first_name"=>"Christian","second_name"=>"Eriksen","player_id"=>"379"),
            array("first_name"=>"Álvaro","second_name"=>"Fernández Carreras","player_id"=>"380"),
            array("first_name"=>"Frederico","second_name"=>"Rodrigues de Paula Santos","player_id"=>"381"),
            array("first_name"=>"Alejandro","second_name"=>"Garnacho","player_id"=>"382"),
            array("first_name"=>"Hannibal","second_name"=>"Mejbri","player_id"=>"383"),
            array("first_name"=>"Tom","second_name"=>"Heaton","player_id"=>"384"),
            array("first_name"=>"Dean","second_name"=>"Henderson","player_id"=>"385"),
            array("first_name"=>"Victor","second_name"=>"Lindelöf","player_id"=>"386"),
            array("first_name"=>"Harry","second_name"=>"Maguire","player_id"=>"387"),
            array("first_name"=>"Kobbie","second_name"=>"Mainoo","player_id"=>"388"),
            array("first_name"=>"Tyrell","second_name"=>"Malacia","player_id"=>"389"),
            array("first_name"=>"Anthony","second_name"=>"Martial","player_id"=>"390"),
            array("first_name"=>"Lisandro","second_name"=>"Martínez","player_id"=>"391"),
            array("first_name"=>"Scott","second_name"=>"McTominay","player_id"=>"392"),
            array("first_name"=>"Teden","second_name"=>"Mengi","player_id"=>"393"),
            array("first_name"=>"Facundo","second_name"=>"Pellistri Rebollo","player_id"=>"394"),
            array("first_name"=>"Raphaël","second_name"=>"Varane","player_id"=>"395"),
            array("first_name"=>"Marcus","second_name"=>"Rashford","player_id"=>"396"),
            array("first_name"=>"Jadon","second_name"=>"Sancho","player_id"=>"397"),
            array("first_name"=>"Luke","second_name"=>"Shaw","player_id"=>"398"),
            array("first_name"=>"Shola","second_name"=>"Shoretire","player_id"=>"399"),
            array("first_name"=>"Donny","second_name"=>"van de Beek","player_id"=>"400"),
            array("first_name"=>"Aaron","second_name"=>"Wan-Bissaka","player_id"=>"401"),
            array("first_name"=>"André","second_name"=>"Onana","player_id"=>"597"),
            array("first_name"=>"Rasmus","second_name"=>"Højlund","player_id"=>"617"),
            array("first_name"=>"Miguel","second_name"=>"Almirón Rejala","player_id"=>"402"),
            array("first_name"=>"Elliot","second_name"=>"Anderson","player_id"=>"403"),
            array("first_name"=>"Harrison","second_name"=>"Ashby","player_id"=>"404"),
            array("first_name"=>"Sven","second_name"=>"Botman","player_id"=>"405"),
            array("first_name"=>"Bruno","second_name"=>"Guimarães Rodriguez Moura","player_id"=>"406"),
            array("first_name"=>"Dan","second_name"=>"Burn","player_id"=>"407"),
            array("first_name"=>"Karl","second_name"=>"Darlow","player_id"=>"408"),
            array("first_name"=>"Martin","second_name"=>"Dubravka","player_id"=>"409"),
            array("first_name"=>"Ryan","second_name"=>"Fraser","player_id"=>"410"),
            array("first_name"=>"Mark","second_name"=>"Gillespie","player_id"=>"411"),
            array("first_name"=>"Anthony","second_name"=>"Gordon","player_id"=>"412"),
            array("first_name"=>"Isaac","second_name"=>"Hayden","player_id"=>"413"),
            array("first_name"=>"Jeff","second_name"=>"Hendrick","player_id"=>"414"),
            array("first_name"=>"Alexander","second_name"=>"Isak","player_id"=>"415"),
            array("first_name"=>"Joelinton Cássio","second_name"=>"Apolinário de Lira","player_id"=>"416"),
            array("first_name"=>"Emil","second_name"=>"Krafth","player_id"=>"417"),
            array("first_name"=>"Garang","second_name"=>"Kuol","player_id"=>"418"),
            array("first_name"=>"Jamaal","second_name"=>"Lascelles","player_id"=>"419"),
            array("first_name"=>"Jamal","second_name"=>"Lewis","player_id"=>"420"),
            array("first_name"=>"Sean","second_name"=>"Longstaff","player_id"=>"421"),
            array("first_name"=>"Javier","second_name"=>"Manquillo Gaitán","player_id"=>"422"),
            array("first_name"=>"Jacob","second_name"=>"Murphy","player_id"=>"423"),
            array("first_name"=>"Nick","second_name"=>"Pope","player_id"=>"424"),
            array("first_name"=>"Matt","second_name"=>"Ritchie","player_id"=>"425"),
            array("first_name"=>"Allan","second_name"=>"Saint-Maximin","player_id"=>"426"),
            array("first_name"=>"Fabian","second_name"=>"Schär","player_id"=>"427"),
            array("first_name"=>"Matt","second_name"=>"Targett","player_id"=>"428"),
            array("first_name"=>"Sandro","second_name"=>"Tonali","player_id"=>"429"),
            array("first_name"=>"Kieran","second_name"=>"Trippier","player_id"=>"430"),
            array("first_name"=>"Kell","second_name"=>"Watts","player_id"=>"431"),
            array("first_name"=>"Joe","second_name"=>"Willock","player_id"=>"432"),
            array("first_name"=>"Callum","second_name"=>"Wilson","player_id"=>"433"),
            array("first_name"=>"Loris","second_name"=>"Karius","player_id"=>"580"),
            array("first_name"=>"Paul","second_name"=>"Dummett","player_id"=>"581"),
            array("first_name"=>"Harvey","second_name"=>"Barnes","player_id"=>"603"),
            array("first_name"=>"Anthony","second_name"=>"Elanga","player_id"=>"378"),
            array("first_name"=>"Brandon","second_name"=>"Aguilera Zamora","player_id"=>"434"),
            array("first_name"=>"Harry","second_name"=>"Arter","player_id"=>"435"),
            array("first_name"=>"Serge","second_name"=>"Aurier","player_id"=>"436"),
            array("first_name"=>"Taiwo","second_name"=>"Awoniyi","player_id"=>"437"),
            array("first_name"=>"Giulian","second_name"=>"Biancone","player_id"=>"438"),
            array("first_name"=>"Willy","second_name"=>"Boly","player_id"=>"439"),
            array("first_name"=>"Josh","second_name"=>"Bowler","player_id"=>"440"),
            array("first_name"=>"Steve","second_name"=>"Cook","player_id"=>"441"),
            array("first_name"=>"Danilo","second_name"=>"dos Santos de Oliveira","player_id"=>"442"),
            array("first_name"=>"Emmanuel","second_name"=>"Dennis","player_id"=>"443"),
            array("first_name"=>"Mohamed","second_name"=>"Dräger","player_id"=>"444"),
            array("first_name"=>"Felipe Augusto","second_name"=>"de Almeplayer_ida Monteiro","player_id"=>",445"),
            array("first_name"=>"Remo","second_name"=>"Freuler","player_id"=>"446"),
            array("first_name"=>"Morgan","second_name"=>"Gibbs-White","player_id"=>"447"),
            array("first_name"=>"Wayne","second_name"=>"Hennessey","player_id"=>"448"),
            array("first_name"=>"Ethan","second_name"=>"Horvath","player_id"=>"449"),
            array("first_name"=>"Brennan","second_name"=>"Johnson","player_id"=>"450"),
            array("first_name"=>"Cheikhou","second_name"=>"Kouyaté","player_id"=>"451"),
            array("first_name"=>"Richie","second_name"=>"Laryea","player_id"=>"452"),
            array("first_name"=>"Orel","second_name"=>"Mangala","player_id"=>"453"),
            array("first_name"=>"Loïc","second_name"=>"Mbe Soh","player_id"=>"454"),
            array("first_name"=>"Scott","second_name"=>"McKenna","player_id"=>"455"),
            array("first_name"=>"Alex","second_name"=>"Mighten","player_id"=>"456"),
            array("first_name"=>"Moussa","second_name"=>"Niakhaté","player_id"=>"457"),
            array("first_name"=>"Lewis","second_name"=>"O'Brien","player_id"=>"458,"),
            array("first_name"=>"Braian","second_name"=>"Ojeda Rodríguez","player_id"=>"459"),
            array("first_name"=>"Jonathan","second_name"=>"Panzo","player_id"=>"460"),
            array("first_name"=>"Omar","second_name"=>"Richards","player_id"=>"461"),
            array("first_name"=>"Gustavo Henrique","second_name"=>"Furtado Scarpa","player_id"=>"462"),
            array("first_name"=>"Jonjo","second_name"=>"Shelvey","player_id"=>"463"),
            array("first_name"=>"Sam","second_name"=>"Surrplayer_idge","player_id"=>"464"),
            array("first_name"=>"Harry","second_name"=>"Toffolo","player_id"=>"465"),
            array("first_name"=>"Hwang","second_name"=>"Ui-jo","player_id"=>"466,"),
            array("first_name"=>"Neco","second_name"=>"Williams","player_id"=>"467"),
            array("first_name"=>"Chris","second_name"=>"Wood","player_id"=>"468"),
            array("first_name"=>"Joe","second_name"=>"Worrall","player_id"=>"469"),
            array("first_name"=>"Ryan","second_name"=>"Yates","player_id"=>"470"),
            array("first_name"=>"Olu","second_name"=>"Aina","player_id"=>"604"),
            array("first_name"=>"Auston","second_name"=>"Trusty","player_id"=>"27"),
            array("first_name"=>"Anel","second_name"=>"Ahmedhodžić","player_id"=>"471"),
            array("first_name"=>"Jordan","second_name"=>"Amissah","player_id"=>"472"),
            array("first_name"=>"George","second_name"=>"Baldock","player_id"=>"473"),
            array("first_name"=>"Chris","second_name"=>"Basham","player_id"=>"474"),
            array("first_name"=>"Sander","second_name"=>"Berge","player_id"=>"475"),
            array("first_name"=>"Jayden","second_name"=>"Bogle","player_id"=>"476"),
            array("first_name"=>"Rhian","second_name"=>"Brewster","player_id"=>"477"),
            array("first_name"=>"Ismaila","second_name"=>"Coulibaly","player_id"=>"478"),
            array("first_name"=>"Adam","second_name"=>"Davies","player_id"=>"479"),
            array("first_name"=>"John","second_name"=>"Egan","player_id"=>"480"),
            array("first_name"=>"John","second_name"=>"Fleck","player_id"=>"481"),
            array("first_name"=>"Wes","second_name"=>"Foderingham","player_id"=>"482"),
            array("first_name"=>"Daniel","second_name"=>"Jebbison","player_id"=>"483"),
            array("first_name"=>"Max","second_name"=>"Lowe","player_id"=>"484"),
            array("first_name"=>"Oliver","second_name"=>"McBurnie","player_id"=>"485"),
            array("first_name"=>"Iliman","second_name"=>"Ndiaye","player_id"=>"486"),
            array("first_name"=>"Rhys","second_name"=>"Norrington-Davies","player_id"=>"487"),
            array("first_name"=>"Oliver","second_name"=>"Norwood","player_id"=>"488"),
            array("first_name"=>"Ben","second_name"=>"Osborn","player_id"=>"489"),
            array("first_name"=>"William","second_name"=>"Osula","player_id"=>"490"),
            array("first_name"=>"Jack","second_name"=>"Robinson","player_id"=>"576"),
            array("first_name"=>"Anis","second_name"=>"Slimane","player_id"=>"587"),
            array("first_name"=>"Yasser","second_name"=>"Larouci","player_id"=>"592"),
            array("first_name"=>"Bénie","second_name"=>"Traoré","player_id"=>"593"),
            array("first_name"=>"Brandon","second_name"=>"Austin","player_id"=>"491"),
            array("first_name"=>"Rodrigo","second_name"=>"Bentancur","player_id"=>"492"),
            array("first_name"=>"Yves","second_name"=>"Bissouma","player_id"=>"493"),
            array("first_name"=>"Bryan","second_name"=>"Gil Salvatierra","player_id"=>"494"),
            array("first_name"=>"Ben","second_name"=>"Davies","player_id"=>"495"),
            array("first_name"=>"Eric","second_name"=>"Dier","player_id"=>"496"),
            array("first_name"=>"Emerson","second_name"=>"Leite de Souza Junior","player_id"=>"497"),
            array("first_name"=>"Fraser","second_name"=>"Forster","player_id"=>"498"),
            array("first_name"=>"Pierre-Emile","second_name"=>"Højbjerg","player_id"=>"499"),
            array("first_name"=>"Harry","second_name"=>"Kane","player_id"=>"500"),
            array("first_name"=>"Dejan","second_name"=>"Kulusevski","player_id"=>"501"),
            array("first_name"=>"Hugo","second_name"=>"Lloris","player_id"=>"502"),
            array("first_name"=>"Giovani","second_name"=>"Lo Celso","player_id"=>"503"),
            array("first_name"=>"James","second_name"=>"Maddison","player_id"=>"504"),
            array("first_name"=>"Tanguy","second_name"=>"Ndombélé Alvaro","player_id"=>"505"),
            array("first_name"=>"Pedro","second_name"=>"Porro","player_id"=>"506"),
            array("first_name"=>"Ivan","second_name"=>"Perišić","player_id"=>"507"),
            array("first_name"=>"Sergio","second_name"=>"Reguilón","player_id"=>"508"),
            array("first_name"=>"Richarlison","second_name"=>"de Andrade","player_id"=>"509"),
            array("first_name"=>"Joe","second_name"=>"Rodon","player_id"=>"510"),
            array("first_name"=>"Cristian","second_name"=>"Romero","player_id"=>"511"),
            array("first_name"=>"Davinson","second_name"=>"Sánchez","player_id"=>"512"),
            array("first_name"=>"Pape Matar","second_name"=>"Sarr","player_id"=>"513"),
            array("first_name"=>"Ryan","second_name"=>"Sessegnon","player_id"=>"514"),
            array("first_name"=>"Oliver","second_name"=>"Skipp","player_id"=>"515"),
            array("first_name"=>"Son","second_name"=>"Heung-min","player_id"=>"516"),
            array("first_name"=>"Djed","second_name"=>"Spence","player_id"=>"517"),
            array("first_name"=>"Japhet","second_name"=>"Tanganga","player_id"=>"518"),
            array("first_name"=>"Destiny","second_name"=>"Udogie","player_id"=>"519"),
            array("first_name"=>"Guglielmo","second_name"=>"Vicario","player_id"=>"520"),
            array("first_name"=>"Alfie","second_name"=>"Whiteman","player_id"=>"521"),
            array("first_name"=>"Manor","second_name"=>"Solomon","player_id"=>"583"),
            array("first_name"=>"Nayef","second_name"=>"Aguerd","player_id"=>"522"),
            array("first_name"=>"Michail","second_name"=>"Antonio","player_id"=>"523"),
            array("first_name"=>"Alphonse","second_name"=>"Areola","player_id"=>"524"),
            array("first_name"=>"Saïd","second_name"=>"Benrahma","player_id"=>"525"),
            array("first_name"=>"Jarrod","second_name"=>"Bowen","player_id"=>"526"),
            array("first_name"=>"Maxwel","second_name"=>"Cornet","player_id"=>"527"),
            array("first_name"=>"Vladimír","second_name"=>"Coufal","player_id"=>"528"),
            array("first_name"=>"Conor","second_name"=>"Coventry","player_id"=>"529"),
            array("first_name"=>"Aaron","second_name"=>"Cresswell","player_id"=>"530"),
            array("first_name"=>"Flynn","second_name"=>"Downes","player_id"=>"531"),
            array("first_name"=>"Emerson","second_name"=>"Palmieri dos Santos","player_id"=>"532"),
            array("first_name"=>"Lukasz","second_name"=>"Fabianski","player_id"=>"533"),
            array("first_name"=>"Pablo","second_name"=>"Fornals Malla","player_id"=>"534"),
            array("first_name"=>"Danny","second_name"=>"Ings","player_id"=>"535"),
            array("first_name"=>"Ben","second_name"=>"Johnson","player_id"=>"536"),
            array("first_name"=>"Thilo","second_name"=>"Kehrer","player_id"=>"537"),
            array("first_name"=>"Divin","second_name"=>"Mubama","player_id"=>"538"),
            array("first_name"=>"Lucas","second_name"=>"Tolentino Coelho de Lima","player_id"=>"539"),
            array("first_name"=>"Gianluca","second_name"=>"Scamacca","player_id"=>"541"),
            array("first_name"=>"Tomáš","second_name"=>"Souček","player_id"=>"542"),
            array("first_name"=>"Nikola","second_name"=>"Vlašić","player_id"=>"543"),
            array("first_name"=>"Kurt","second_name"=>"Zouma","player_id"=>"544"),
            array("first_name"=>"Angelo","second_name"=>"Ogbonna","player_id"=>"577"),
            array("first_name"=>"Rayan","second_name"=>"Aït-Nouri","player_id"=>"545"),
            array("first_name"=>"Daniel","second_name"=>"Bentley","player_id"=>"546"),
            array("first_name"=>"Bendegúz","second_name"=>"Bolla","player_id"=>"547"),
            array("first_name"=>"Hugo","second_name"=>"Bueno López","player_id"=>"548"),
            array("first_name"=>"Francisco Jorge","second_name"=>"Tomás Oliveira","player_id"=>"549"),
            array("first_name"=>"Luke","second_name"=>"Cundle","player_id"=>"550"),
            array("first_name"=>"Craig","second_name"=>"Dawson","player_id"=>"551"),
            array("first_name"=>"Fábio","second_name"=>"Silva","player_id"=>"552"),
            array("first_name"=>"Gonçalo Manuel","second_name"=>"Ganchinho Guedes","player_id"=>"554"),
            array("first_name"=>"Joe","second_name"=>"Hodge","player_id"=>"555"),
            array("first_name"=>"Ki-Jana","second_name"=>"Hoever","player_id"=>"556"),
            array("first_name"=>"Hwang","second_name"=>"Hee-chan","player_id"=>"557"),
            array("first_name"=>"João Victor","second_name"=>"Gomes da Silva","player_id"=>"559"),
            array("first_name"=>"Jonathan","second_name"=>"Castro Otto","player_id"=>"560"),
            array("first_name"=>"Bruno","second_name"=>"Cavaco Jordão","player_id"=>"561"),
            array("first_name"=>"Sasa","second_name"=>"Kalajdzic","player_id"=>"562"),
            array("first_name"=>"Max","second_name"=>"Kilman","player_id"=>"563"),
            array("first_name"=>"Tom","second_name"=>"King","player_id"=>"564"),
            array("first_name"=>"Mario","second_name"=>"Lemina","player_id"=>"565"),
            array("first_name"=>"Matheus Luiz","second_name"=>"Nunes","player_id"=>"566"),
            array("first_name"=>"Pedro","second_name"=>"Lomba Neto","player_id"=>"567"),
            array("first_name"=>"Daniel","second_name"=>"Castelo Podence","player_id"=>"568"),
            array("first_name"=>"José","second_name"=>"Malheiro de Sá","player_id"=>"569"),
            array("first_name"=>"Pablo","second_name"=>"Sarabia","player_id"=>"570"),
            array("first_name"=>"Matija","second_name"=>"Šarkić","player_id"=>"571"),
            array("first_name"=>"Nélson","second_name"=>"Cabral Semedo","player_id"=>"572"),
            array("first_name"=>"Toti António","second_name"=>"Gomes","player_id"=>"573"),
            array("first_name"=>"Boubacar","second_name"=>"Traoré","player_id"=>"574"),
            array("first_name"=>"Matheus","second_name"=>"Santos Carneiro Da Cunha","player_id"=>"590"),
            array("first_name"=>"Matt","second_name"=>"Doherty","player_id"=>"598"),
        );

        Player::insert($players);
    }
}
